### ISSUE TITLE
Custom views

### ISSUE THREAD

**Issue by azuline** [azuline/rose#17]
Create custom views of tracks and releases based on filters.

Stored smart playlists/collages are trivial. To make the experience ergonomic, we should have a config refresh option that reads pids and sends signal to refresh config.

**Comment by azuline** [comment]
Potentially subsumes #20, if we reimplement all existing views as "smart views."

Smart views would:
- Be defined in the configuration file.
- Be able to filter out `releases, tracks, artists, labels, genres` (e.g. all artists with k-pop release) with rule engine matchers.
- Artists, genres, and labels would have a releases or tracks children option.
- Have their own path templates.

We can have a default set of views implemented as smart rules, with the option to override them and rebuild your own from scratch. IDK if I want to have a global nuke or an "extend" option. Maybe

```toml
[virtual_views.all_releases]
enabled = false  # Defaults to true when undefined.

[virtual_views.my_custom_view]
name = "My Custom View"
path_templates.release = ""
path_templates.track = ""
hierarchy = ["artists", "tracks"]  # or just ["tracks"], or ["releases"], or ["labels", "releases"], etc.
matcher = "genre:K-Pop"
```
