### ISSUE TITLE
Allow ignoring values in rules

### ISSUE THREAD

**Issue by azuline** [azuline/rose#32]
```toml
matcher = "trackartist,albumartist: & "
actions = ["split: & "]
ignore = ["Eli & Fur"]
```

```bash
$ rose rules run "trackartist,albumartist: & " "split: & " --ignore "trackartist,albumartist:Eli & Fur"
```
